### ISSUE TITLE
Create a logo for this app

### ISSUE THREAD

**Issue by MegaMaxim10** [MegaMaxim10/MIUFnCurvesDrawer#1]

**Comment by andeladenaro** [comment]
Hi.. My name is Andela Denaro, and I want to propose logo for your project.
Here's my design.

![curves drawer](https://user-images.githubusercontent.com/35057858/45875443-e437cc80-bdc1-11e8-82df-46e8e48ffd96.png)

I would appreciate hearing your opinion on this. Kind regards.

**Comment by MegaMaxim10** [comment]
Hi Andela, my name is Ndadji Maxime. I really like your design! It's really in the spirit of the application that I'm trying to build. Wow, you're pretty good huh. Thank you very much for your interest and I hope we will collaborate throughout this great adventure?

**Comment by andeladenaro** [comment]
Yes sure.. Challenge accepted. 
So what do you think? If it suits your mind, I will provide the original file for this project.

**Comment by MegaMaxim10** [comment]
Yes that corresponds to my expectations. It would be interesting to have a version without the text that will be used as the icon of the desktop application.

**Comment by andeladenaro** [comment]
I've provided the icon files and also full version of file. Here's [Google Drive](https://drive.google.com/drive/folders/1zYjGTPMVEbv3pm6R5nhJDF3no9fkwyW1?usp=sharing)'s sharing file. Feel free to ask me if you need more.

**Comment by MegaMaxim10** [comment]
Ok thanks!
